version: "3.8"

services:
  postgresql:
    image: postgres:latest
    container_name: 'bap-connect'
    environment:
      POSTGRES_DB: bap-connect
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - "55432:5432"